/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:71fcb38a-b7d0-417b-b09b-37f1213f129c",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_r09zOyQN2",
    "aws_user_pools_web_client_id": "5lq06dbf1f6g3ic0ieo8oeum4j",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://6utt2vkvhveo5kgerlbu7e56ka.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-tmgzhyw2yffqzozbqecaiaduoe"
};


export default awsmobile;
